### ISSUE TITLE
Certificate Generation Failing

### ISSUE THREAD

**Issue by bmkeller** [gurumitts/pylutron-caseta#100]
### Problem
Calling await async_pair(SERVER_ADDRESS) always returns an SSL failure: **_verify failed: self signed certificate in certificate chain_**

>   File "/Users/mike/coding/pylutron-caseta/do_pairing.py", line 171, in async_pair
>     cert_pem, ca_pem = await _async_generate_certificate(
>   File "/Users/mike/coding/pylutron-caseta/do_pairing.py", line 205, in _async_generate_certificate
>     reader, writer = await asyncio.wait_for(
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 478, in wait_for
>     return fut.result()
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 52, in open_connection
>     transport, _ = await loop.create_connection(
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
>     transport, protocol = await self._create_connection_transport(
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
>     await waiter
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
>     ssldata, appdata = self._sslpipe.feed_ssldata(data)
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
>     self._sslobj.do_handshake()
>   File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 944, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)  
> 

### Steps to reproduce
1. Open python REPL with asyncio module
`$ python -m asyncio`
2. Import async_pair
`>>> from pylutron_caseta.pairing import async_pair`
3. Call async_pair with a valid or invalid server address
`>>> await async_pair("192.168.1.255")`

### Information
OS: Mac Big Sur 11.3.1
OS Version: 11.3.1
Python: 3.9.1

**Comment by mdonoughe** [comment]
There is something going on with your network if you get that error with an invalid server address. Check `openssl s_client -showcerts -connect 192.168.1.255:8083`. It should mention this certificate chain

```
C = US, ST = Pennsylvania, O = "Lutron Electronics Co., Inc.", L = Coopersburg, CN = Caseta Smart Bridge
C = US, ST = Pennsylvania, O = "Lutron Electronics Co., Inc.", L = Coopersburg, CN = Caseta Local Access Protocol Cert Authority
C = US, ST = Pennsylvania, O = "Lutron Electronics Co., Inc.", L = Coopersburg, CN = Residential Local Access Protocol Certificate Authority
```

**Comment by mdonoughe** [comment]
This could also happen if you try to connect to a newer system such as RA3. Maybe the latest dev branch code works.
