### ISSUE TITLE
RA3/QSX Button LED Names don't identify the Keypad and Button

### ISSUE THREAD

**Issue by danaues** [gurumitts/pylutron-caseta#108]
@cbw, Amazing work on the QSX support, and for adding LED and button press support.

I've been testing with my setup, and I think it would help to use a more meaningful name for the Keypad LEDs

I have 2 keypads in this area, a 3BRL and a 4B.  It's hard to tell which led these belong too.
Ideally they would be named "LED_Hallway Main Stairs_Position 1_Button2" or something like that.

![image](https://user-images.githubusercontent.com/24459240/187509638-8d7d9e35-746d-4005-a3be-38f73931b23d.png)

**Comment by cbw** [comment]
Thanks for catching that! I may have had a regression, thought I fixed it (or perhaps it was in the HA side of the code I was working on). I'll take a look tonight.

**Comment by danaues** [comment]
My system is returning an empty string for engraving.  The engraving key exists, so it doesn't get assigned 'None', just returns the empty string.

https://github.com/gurumitts/pylutron-caseta/blob/72fd4ca85d591a35616d92f7ec0d1fcbb839f906/pylutron_caseta/smartbridge.py#L918-L927

**Comment by danaues** [comment]
For the naming, it would be nice to keep the button naming consistent with the Keypad naming.

https://github.com/gurumitts/pylutron-caseta/blob/72fd4ca85d591a35616d92f7ec0d1fcbb839f906/pylutron_caseta/smartbridge.py#L958-L970

**Comment by danaues** [comment]
This is what mine looks like if I name it this way.

They keypad device name matches the LED's below it.  (1st keypad has engraving names, 2nd does not)
![image](https://user-images.githubusercontent.com/24459240/187550340-7ca60e96-bed1-4166-927e-63361475ddb6.png)

**Comment by cbw** [comment]
Great suggestions – incorporated these and tested, looks good on my test QSX processor as well. Submitted #110 with this update.

Now I just need to get my HomeAssistant button code cleaned up and submitted! The HA button situation is a little messy, and may take some refactoring to make clearer with what's in there now for handling Pico events.

**Comment by danaues** [comment]
Let me know if there is anything I can help with, I"m happy to help test.

**Comment by cbw** [comment]
@danaues any tips from your experiencing making a PR on homeassistant-core, especially on testing? Are you on the Home Assistant discord by chance?

**Comment by danaues** [comment]
@cbw, unfortunately, I'm not on the discord. I could join though.
bdraco was great at helping out, was quick to respond and was eager to have new contributors.  
I think he's travelling right now, but he will approve and be a great resource.

Do you want me to test anything before you create the PR?
