### ISSUE TITLE
support for Raise/Lower button on ra3 sunnata keypads?

### ISSUE THREAD

**Issue by centrino66** [gurumitts/pylutron-caseta#125]
Hi there,

First I really appreciate the effort here by bringing in RA3 support. I am finally able to integrate Phillips Hue onto the Sunnata keypads!

The question is around R3 sunnata keypads Raise/Lower buttons. They are not showing in the entities. Is there a plan to bring the support for these 2 little things? Thank you!

![image](https://user-images.githubusercontent.com/101959515/194776199-cfb7b62e-324d-4e8c-83f9-46b1918d5326.png)

**Comment by danaues** [comment]
Hi @centrino66 

These buttons are supported as Device Triggers for automations.

If you create an automation 
Click "+Add Trigger"
Select "Device"
Choose your Sunnata 3BRL Keypad from the list
On the trigger dropdown, you will see all the buttons, including the raise and lower buttons

The entities you are seeing in your attachment represent the LEDs associated with the first 3 buttons.  They are "switches" and you can turn the LED light on/off using those entities.

There is a future update coming that will allow you to press the buttons too (including the raise/lower buttons)

**Comment by danaues** [comment]
All the features required for these Keypads have already been implemented in pylutron-caseta.

Can you please close the issue?

Thanks.

**Comment by centrino66** [comment]
Ah I see, thanks for the explanations. Closing the ticket.
