### ISSUE TITLE
Support for Sunnata RF Hybrid Keypads

### ISSUE THREAD

**Issue by AP-Foundation** [gurumitts/pylutron-caseta#135]
Hi there,

We currently have Sunnata RF Dimmers and this library is working great! Thank you. Does the library support the Sunnata RF Hybrid Keypads as well? These are the keypads with integrated dimmers. I searched around the source code and couldn't find a reference to the model numbers. 

Models:
RRST-HN4B-(XX)
RRST-HN3RL-(XX)
RRST-HN2B-(XX)

Thank you,
AP

**Comment by mdonoughe** [comment]
I think they should work. There's a reference to Sunnata keypads here: https://github.com/gurumitts/pylutron-caseta/blob/b560e5d567af313dc1dbbed63fd7e97e2ed84bc5/pylutron_caseta/__init__.py#L48-L69

**Comment by mdonoughe** [comment]
If it doesn't work, try with this version of `__init__.py`. https://github.com/gurumitts/pylutron-caseta/blob/ad19ad0fa1c2282eb441e62b8afab7542f4cb692/pylutron_caseta/__init__.py

**Comment by AP-Foundation** [comment]
Thank you! Our hybrid keypads should arrive early February and we'll report back then.

**Comment by AP-Foundation** [comment]
Just a quick update: we installed a Sunnata Hybrid Keypad today and Home Assistant (via the Caseta integration) is able to successfully detect / command the internal dimmer. However, the keypad buttons / LEDs are not detected. I'm not familiar on the process to manually apply the patch you referenced in Home Assistant OS, but will report back once I figure that out. 

We have some regular Sunnata Keypads (without internal dimmers) and the integration does detect those keypad buttons / LEDs.

**Comment by AP-Foundation** [comment]
The patch worked! The Hybrid keypad now shows as two devices in Home Assistant: a "keypad" and a "light" (for the local load). I quickly tested both devices and they seem to work as expected. 

For others, I was able to manually apply the patch via the console as follows (assuming you already have the Lutron Caseta integration already working):

1. Access Home Assistant OS via the console and login with user "root" and no password. 
2. Run `docker exec -it $(docker ps -f name=homeassistant -q) bash`, which will drop you into a bash shell
3. Within the bash shell, run `pip uninstall pylutron-caseta` to remove the version of the library that is included with the integration
4. Install latest dev branch with above patch included: `pip install git+https://github.com/gurumitts/pylutron-caseta@dev`
5. Reboot via the GUI

Thanks again for the help here.

**Comment by AP-Foundation** [comment]
Hmm... for some odd reason the newly added keypad device just stopped responding. I tried deleting both the dimmer & keypad devices, and also reloading the Caseta integration, but now the keypad device is not being detected (just the dimmer). I suspect the Ra3 processor is acting up but I'm not sure how to debug via Home Assistant (tried rebooting both) 

@mdonoughe do you have any ideas?

**Comment by mdonoughe** [comment]
Are you running Home Assistant Core? If you're using Home Assistant OS or something, changes you make in the container image, such as pip installing things, may be reverted by maintenance tasks. If you install into the site-packages folder in your configuration it will persist, but you'll need to remember to delete it from there later.

**Comment by AP-Foundation** [comment]
Ah yes -- Home Assistant OS was reverting to v0.17.1 upon system reboot / reload of the Caseta integration. Manually edited the __init__.py file and all is working again. False alarm. Thanks again.
