### ISSUE TITLE
Support for Homeworks QS Connect Bridge 

### ISSUE THREAD

**Issue by ronluna** [gurumitts/pylutron-caseta#151]
Since the connect bridge used for homeworks qs uses the same leap protocol. would it possible to add them to the list of supported devices ? it would also open the door for the previous generation of Ketra devices that Homeworks QS supports.

**Comment by cbw** [comment]
Have you tried the "Lutron" or "homeworks" integrations with the telnet LIP protocol? Not sure if the connect bridge's LEAP is compatible with this library. I have QSX, so not able to test it.

**Comment by ronluna** [comment]
I've tried the lutron connect bridge for homeworks qs and ra2 with pylutron-caseta but they both failed during the pairing process. and seems like that only through the official Lutron app the telnet  service can be enabled on the bridge and only QSX and Caseta system can use this app. Which this in fact corroborates your previous comment... pylutron-caseta won't work!
