### ISSUE TITLE
get_lutron_cert.py not working

### ISSUE THREAD

**Issue by murray484** [gurumitts/pylutron-caseta#26]
Hello,

I'm trying to use the get_lutron_cert.py script to authorize my casesta hub on my HomeAssistant server.  Each time I run the script, I get the following error after I paste the response code from Lutron:

```
Traceback (most recent call last):
  File "get_lutron_cert.py", line 78, in <module>
    with open('caseta.crt', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'caseta.crt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_lutron_cert.py", line 124, in <module>
    app_cert = pairing_response["remote_signs_app_certificate"]
KeyError: 'remote_signs_app_certificate'
```

I'm using the latest version of the script, using python3 on a mac.  Does anyone know what is causing this?

Thanks!

**Comment by murray484** [comment]
Thanks - I actually ran it in a virtualenv using the instructions at the top of the script when I executed it.

**Comment by mdonoughe** [comment]
Does this script work better? https://github.com/mdonoughe/pylutron-caseta/blob/content-type/get_lutron_cert.py

I successfully used it to generate certificates using Python 3.6.5 installed from pyenv on Linux.

**Comment by murray484** [comment]
I just tried it - same error as before.

**Comment by mdonoughe** [comment]
It works fine for me on OS X 10.11 and Python 3.6.5 installed from Python.org.

**Comment by murray484** [comment]
Figured it out - the script @mdonoughe shared works, but only if you have devices added to your lutron system.  I haven't installed my switches yet.  Once I added the pico remote to the system it works perfectly.
