### ISSUE TITLE
Recovering from power outage

### ISSUE THREAD

**Issue by sweharris** [gurumitts/pylutron-caseta#33]
It's not clear if this is a Home Assistant or pylutron-caseta issue...

My Caseta bridge had a power outage (a contractor overloaded the circuit and tripped the breaker switch).  After rebooted, HA was unable to talk to the bridge and all attempts timed out.

Logs at that time...

```
2019-04-04 18:17:10 ERROR (MainThread) [homeassistant.core] Error doing job: Fat
al read error on socket transport
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/asyncio/selector_events.py"
, line 724, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host

```

Restarting the home assistant process fixed the issue.

**Comment by mdonoughe** [comment]
It's probably a pylutron-caseta issue that you couldn't talk to the bridge, but it's not clear whether that error is related or not.

I tried to make some improvements to reconnection in #30, but even with those fixes I still have had to restart home-assistant once or twice to get pylutron-caseta working again.

**Comment by mdonoughe** [comment]
I'm going to close this one. OSError is now handled the same as a connection error because Python sometimes reports OSError when it fails to connect. After two seconds the connection should be retried.
