### ISSUE TITLE
Lights lack SUPPORT_TRANSITION

### ISSUE THREAD

**Issue by erenfro** [gurumitts/pylutron-caseta#37]
I noticed that Lutron Caseta specificially lacks the SUPPORT_TRANSITION effects, yet the Lutron Caseta dimmers definitely seem to have support.

**Comment by mdonoughe** [comment]
The dimmers transition, at least when you physically press the button, but the Android app doesn't seem to so I'm not sure if there's a good way to do it.

**Comment by bdraco** [comment]
There is a `GoToDimmedLevel` command but thats all I could find

**Comment by swails** [comment]
What do you mean by support transition?

**Comment by mdonoughe** [comment]
For Hue there's a way to specify how long the lights should transition between off and on, but I haven't found anything similar for Caseta.

**Comment by swails** [comment]
This worked for me:

```json
{
    "CommuniqueType": "CreateRequest",
    "Header": {
        "Url": "/zone/7/commandprocessor"
    },
    "Body": {
        "Command": {
            "CommandType": "GoToDimmedLevel",
            "DimmedLevelParameters": {
                "Level": 0,
                "FadeTime":"00:00:10"
            }
        }
    }
}
```

But that would require reworking pylutron-caseta's `set_value` implementation to treat switches and dimmers separately.

**Comment by mdonoughe** [comment]
How do you both know about GoToDimmedLevel but Google does not?

**Comment by bdraco** [comment]
> How do you both know about GoToDimmedLevel but Google does not?

https://ibotpeaches.github.io/Apktool/

**Comment by mdonoughe** [comment]
I was sure the app did not support that, but it does contain GoToDimmedLevel. I'm not sure what for.

**Comment by mdonoughe** [comment]
After merging #56 I have code for this on https://github.com/mdonoughe/pylutron-caseta/tree/dimmedlevel .

I'm using this in Home Assistant by copying my custom lutron_caseta folder to config/custom_components. The dependency update in manifest.json causes my dimmedlevel branch to be copied to config/deps. https://github.com/mdonoughe/home-assistant/tree/caseta-0.7/homeassistant/components/lutron_caseta
