### ISSUE TITLE
What's the process for cutting a new release?

### ISSUE THREAD

**Issue by swails** [gurumitts/pylutron-caseta#43]
#41 added support for occupancy sensors, which I plan to add support for in Home Assistant.  However, that would require pinning to a pylutron-caseta release that supports occupancy sensors/groups, which doesn't currently exist.

What needs to be done to cut a new release?  And when it happens, can it be 0.6.0 (so at least I know what to pin in the home assistant PR I plan on raising soon)?

**Comment by mdonoughe** [comment]
If you've got it working in Home Assistant and don't think you'll need more changes I can make a new release. 0.6.0 sounds okay to me.

**Comment by swails** [comment]
I'll raise the HA PR when I have it working on my system.  I'll pin to 0.6.0 in that PR.

**Comment by swails** [comment]
https://github.com/home-assistant/core/pull/33032

I've been running it as a custom component in my hub for about a week or so and everything seems to work:

![occupancy-example](https://user-images.githubusercontent.com/779022/77138014-93507500-6a46-11ea-96cc-6dd4da97ca8b.jpg)

**Comment by swails** [comment]
Can we cut the new release?  The home-assistant PR is approved, but won't work until pylutron-caseta-0.6.0 is available.

**Comment by mdonoughe** [comment]
0.6.0 is uploaded to pypi.

**Comment by swails** [comment]
Thanks!
