### ISSUE TITLE
Lutron Caseta quits working with Home Assistant after a while

### ISSUE THREAD

**Issue by TonyApuzzo** [gurumitts/pylutron-caseta#45]
Is there any chance that the recent changes for 0.6.0 will fix the issue documented here: https://github.com/home-assistant/core/issues/31361 ?

Otherwise, is this a problem that should be addressed in this repo or is it a Home Assistant issues?  Any other debugging that I can do, please let me know.

**Comment by mdonoughe** [comment]
I don't think so. I haven't been having this issue.

Home Assistant has been using pylutron_caseta 0.5.1 since 0.103.0. pylutron_caseta 0.5.1 fixed reconnection problems I used to have: https://github.com/gurumitts/pylutron-caseta/milestone/1?closed=1

Why does your Python raise OSError 113 instead of ConnectionError like it's supposed to when it has a connection error? :( Should the retry loop just ignore any OSError?

**Comment by TonyApuzzo** [comment]
I'm pretty clueless to be answering your questions :-)  

I only know enough to track down the libraries through the requirements.txt file.

The issue does seem to go away (temporarily) when restarting HA, so it stands to reason that retrying instead of just giving up on that error could be beneficial.

I see that HA integrated 0.6.0 yesterday but they don't have an official build using it released yet.

Once they release a beta with 0.6.0 integrated, I'll install it and see if the problem crops up or not -- it's tricky since nobody seems to know what triggers the issue other than waiting hours or days.

**Comment by clmw83** [comment]
I think I've got the same issue (random disconnects which cause pylutron_caseta to no longer work in HA until a restart).  

Looking at it a bit, asyncio does seem throw an OSError when it has issues with its socket connections (this looks like periodically it may just gets a "No Route to Host Error" -  not sure the underlying cause).   I think just catching OSError to trigger a reconnect in the monitor loop (line 275) may fix this.

**Comment by TonyApuzzo** [comment]
It appears, based on work happening in the `pylutron-caseta` base library. that the devs are attempting to have this patched for the 0.108 release.  The current 0.108.4 beta does not have the fix yet from what I can tell looking at github though.
