### ISSUE TITLE
Subscribing to Pico Remotes and Plug-In Dimmers does nothing

### ISSUE THREAD

**Issue by ssnover95** [gurumitts/pylutron-caseta#46]
Currently trying to get my Philips Hue bulbs to be controllable from my Pico Remote, however this library doesn't quite behave how I'd expect.

Here's a short sample of what I'm attempting:
```
from pylutron_caseta import smartbridge
import time
import asyncio

async def main():
    bridge = smartbridge.Smartbridge.create_tls("<ip>", "caseta.key", "caseta.crt", "caseta-bridge.crt")
    await bridge.connect()
    picos = bridge.get_devices_by_type("Pico3ButtonRaiseLower")
    assert(len(picos) > 0)
    [bridge.add_subscriber(pico['device_id'], lambda: print("Hello from Pico")) for pico in picos]
    while True:
        time.sleep(1)

asyncio.run(main())
```
I have two Pico remotes, which I've verified can be seen on the Bridge with the `get_devices()` method. I've also tried my PlugInDimmer. It does not appear that button presses trigger the callback registered as a subscriber.

**Comment by ssnover95** [comment]
Additional detail, as I debugged further: every Pico remote button press triggers a TLS message from the bridge to my computer, indicating some kind of LEAP traffic. I observed this consistently with both remotes in Wireshark.

**Comment by mdonoughe** [comment]
I doubt the bridge sends a notification when the button is pressed unless you've somehow asked for it. @swails just added something for that, but I think it's different for the three-button remotes.

**Comment by swails** [comment]
The code I added was to make a LEAP subscription to occupancy groups so it will report back when the groups are reported as occupied or vacant.

The same doesn't (yet) work for Pico remotes as far as I'm aware.  I've read that you can use the pylutron bindings (that uses telnet) if you have a PRO bridge (non-PRO bridges don't support telnet).

> Additional detail, as I debugged further: every Pico remote button press triggers a TLS message from the bridge to my computer, indicating some kind of LEAP traffic.

You're probably seeing the light level update.  If the Pico is programmed to *something*, then that something reports its new level following the Pico button press and that level gets reported by the bridge to each connection.

You can set the log level in the library to DEBUG and see every LEAP message that gets sent by the bridge to your computer.

**Comment by ssnover95** [comment]
I'll close this issue then. A potential workaround if you have extra plug-in dimmers is to just set one up without any loads and assign a Pico to control it. Then you'll be able to monitor changes in it's state to pass onto whatever you want to control.
