### ISSUE TITLE
Problem creating the files

### ISSUE THREAD

**Issue by Hopdevil1** [gurumitts/pylutron-caseta#51]
When I try to run the script, I get this error. Any thoughts? I have installed OpenSSL
root@buzzs-laptop:/home/buzz# python get_lutron_cert.py
Traceback (most recent call last):
  File "get_lutron_cert.py", line 31, in <module>
    from OpenSSL import SSL, crypto
ImportError: No module named OpenSSL
root@buzzs-laptop:/home/buzz#

**Comment by swails** [comment]
You need to install the python bindings to OpenSSL, not just OpenSSL itself.

**Comment by mdonoughe** [comment]
Did you follow the steps at the top of the file?

**Comment by Hopdevil1** [comment]
Sorry, I'm a newbee and missed that. 
That worked but now it errors out at this point.
root@buzzs-laptop:/home/buzz/Downloads/pylutron-caseta-dev# python get_lutron_cert.py
Traceback (most recent call last):
  File "get_lutron_cert.py", line 38, in <module>
    [x509.NameAttribute(NameOID.COMMON_NAME, "get_lutron_cert.py")]
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 87, in __init__
    "value argument must be a text type."
TypeError: value argument must be a text type.
root@buzzs-laptop:/home/buzz/Downloads/pylutron-caseta-dev# 
Very sorry to bother you.

**Comment by mdonoughe** [comment]
That's probably a Python 2.7 problem. Try with Python 3. You might have it as `python3` on your system.

**Comment by joebloggins** [comment]
> You need to install the python bindings to OpenSSL, not just OpenSSL itself.

Could you provide the command(s) to achieve that?

**Comment by joebloggins** [comment]
> > You need to install the python bindings to OpenSSL, not just OpenSSL itself.
> 
> Could you provide the command(s) to achieve that?

Found the issue.  I needed to be root to install OpenSSL:  "sudo pip install pyOpenSSL==19.1.0"
