### ISSUE TITLE
Bridge Reconnect during set_value is faing

### ISSUE THREAD

**Issue by jimboca** [gurumitts/pylutron-caseta#59]
I'm updating the ISY nodeserver written by @timekillerj and referencing your dev branch for testing.  It all works great until it needs to reconnect to the bridge.  The call below is executing:
` return self.controller.mainloop.run_until_complete(self.sb.set_value(device, value))`
But fails with BridgeDisconnectedError even though it says reconnect is happening?   Is this a bug or am I doing something wrong?

```
2020-10-03 18:16:35,709 Controller polyinterface      INFO     LutronCasetaNodes:send_command: send_command result: None
2020-10-03 19:23:44,111 Controller polyinterface      INFO     LutronCasetaNodes:setClose: setClose: command {'address': 'device8', 'cmd': 'DOF', 'query': {}}
2020-10-03 19:23:44,111 Controller polyinterface      INFO     LutronCasetaNodes:send_command: Sending value to Smart Bridge for device 8: 0
2020-10-03 19:23:44,112 Controller polyinterface      INFO     LutronCasetaNodes:send_command: is_connected=True
2020-10-03 19:23:44,114 Controller pylutron_caseta.leap DEBUG    leap:request: sending b'{"CommuniqueType": "CreateRequest", "Header": {"ClientTag": "b45c573b-19d3-4bf9-8ffd-b84f6a816e22", "Url": "/zone/4/commandprocessor"}, "Body": {"Command": {"CommandType": "GoToLevel", "Parameter": [{"Type": "Level", "Value": 0}]}}}'
2020-10-03 19:23:44,116 Controller pylutron_caseta.leap DEBUG    leap:request: sending b'{"CommuniqueType": "ReadRequest", "Header": {"ClientTag": "600479c8-72e6-4990-9edf-b39cee083173", "Url": "/server/1/status/ping"}}'
2020-10-03 19:23:44,117 Controller pylutron_caseta.smartbridge WARNING  smartbridge:_monitor_once: LEAP session ended. Reconnecting...
2020-10-03 19:23:46,120 Controller pylutron_caseta.smartbridge DEBUG    smartbridge:_monitor_once: Connecting to Smart Bridge via SSL
2020-10-03 19:23:46,127 Controller polyinterface      ERROR    polyinterface:_parseInput: _parseInput: failed device8.runCmd(DOF) name 'pylutron_caseta' is not defined
Traceback (most recent call last):
  File "/home/pi/development/udi-poly-lutroncaseta/lutron_caseta_nodes/LutronCasetaNodes.py", line 30, in set_value
    return self.controller.mainloop.run_until_complete(self.sb.set_value(device, value))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/development/udi-poly-lutroncaseta/pylutron_caseta/smartbridge.py", line 282, in set_value
    "Parameter": [{"Type": "Level", "Value": value}],
  File "/home/pi/development/udi-poly-lutroncaseta/pylutron_caseta/smartbridge.py", line 235, in _request
    timeout=REQUEST_TIMEOUT,
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/development/udi-poly-lutroncaseta/pylutron_caseta/leap.py", line 60, in request
    return await future
pylutron_caseta.BridgeDisconnectedError
```

**Comment by mdonoughe** [comment]
You should get a BridgeDisconnectedError if your request is in flight when the connection is lost because there is no way to know whether the command reached the bridge.

Also, with the current implementation I think you will get a BridgeDisconnectedError if you try to send new commands before the bridge has reconnected. Maybe requests starting while a connect is in progress could wait for a new connection to be established, but the time to successfully establish a connection is usually so short it shouldn't matter unless somebody wants to retry a failed command ASAP.

**Comment by jimboca** [comment]
Thanks, so it is failing when I call set_value, should I just retry again when I get the BridgeDisconnectedError?

**Comment by mdonoughe** [comment]
Do you know why you're needing to reconnect? I think I need to reconnect less than once a week.

**Comment by jimboca** [comment]
No I have no idea, nothing shows before that in the log. I had worked on adding more debugging to your code a while back, but could never figure out why. From what I remember, it seems the ping was not working? But I could be thinking about something else all together.

**Comment by mdonoughe** [comment]
I see `run_until_complete(self.sb.set_value(device, value))` in the traceback. Are you maybe only running the event loop for milliseconds at a time when you are interacting with the bridge? The event loop periodically wakes up and sends a ping to the bridge to keep the TCP connection alive and detect if the bridge is still there (sometimes the bridge reboots itself for updates). If the event loop is only running intermittently, the bridge may be dropping the connection, or pylutron_caseta may be interpreting the lapses in execution as ping timeouts and dropping the connection itself, or maybe even the receive buffer is filling up because the event loop is also necessary for processing messages sent from the bridge.

pylutron_caseta does not require it's own dedicated thread, but if you're not already using asyncio you will need a thread to run the event loop.

Alternatively, if you don't care about the bridge pushing status updates, you could disconnect from the bridge between requests. Every time you wanted to interact with the bridge you would need to connect first.

**Comment by jimboca** [comment]
Yes, I run the bridge in it's own thread
```
    async def _bridge_connect(self):
        self.sb = Smartbridge.create_tls(hostname=self.lutron_bridge_ip,
                                         keyfile='./caseta.key',
                                         certfile='./caseta.crt',
                                         ca_certs='caseta-bridge.crt',
                                         )
        await self.sb.connect()
        if self.sb.is_connected():
            LOGGER.info("Successfully connected to bridge!")
        else:
            LOGGER.error("Could not connect to bridge")
        self.connecting = False

    def _bridge_start(self):
        try:
            mainloop.run_until_complete(self._bridge_connect())
        except:
            LOGGER.error("Bridge connect failed")

    def bridge_connect(self):
        self.connecting = True
        self.connect_thread = Thread(target=self.__bridge_start)
        self.connect_thread.start()
```

Is anything logged when the ping runs?  I expected to see something but I never do.

**Comment by mdonoughe** [comment]
If you have the debug logging enabled you should be seeing the ping messages being sent.

Your thread only runs as long as the bridge takes to connect. You probably want to do something like this instead:

```py
    async def _bridge_connect(self):
        self.sb = Smartbridge.create_tls(hostname=self.lutron_bridge_ip,
                                         keyfile='./caseta.key',
                                         certfile='./caseta.crt',
                                         ca_certs='caseta-bridge.crt',
                                         )
        await self.sb.connect()
        if self.sb.is_connected():
            LOGGER.info("Successfully connected to bridge!")
        else:
            LOGGER.error("Could not connect to bridge")
        self.connecting = False

    def bridge_connect(self):
        self.connecting = True
        self.connect_thread = Thread(target=mainloop.run_forever)
        self.connect_thread.start()
        mainloop.call_soon_threadsafe(_bridge_connect)
```

`call_soon_threadsafe` will let you enqueue work to the event loop from outside. This code doesn't deal with cleaning up the thread, so if you call `bridge_connect` multiple times you'll get multiple threads.

**Comment by jimboca** [comment]
Thank you!  I tried real quick and get
`2020-10-04 14:34:22,527 Thread-1   py.warnings        WARNING  warnings:_showwarnmsg: /usr/lib/python3.7/asyncio/events.py:88: RuntimeWarning: coroutine 'LutronCasetaController._bridge_connect' was never awaited`
I'm leaving now but will look again when I return.

**Comment by mdonoughe** [comment]
Hmm https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading says it should be `asyncio.run_coroutine_threadsafe(self._bridge_connect(), mainloop)` instead of `mainloop.call_soon_threadsafe(_bridge_connect)`.

**Comment by jimboca** [comment]
That works perfectly!  Thank you very much.  I use that to change the settings as well which work great
`        result = asyncio.run_coroutine_threadsafe(self.sb.set_value(device, value), self.controller.mainloop)`
And now when I open and close from the app I get the callback's right away.  Very cool.
