### ISSUE TITLE
Lutron Appliance Module support

### ISSUE THREAD

**Issue by YourMom11** [gurumitts/pylutron-caseta#75]
Hi there. I hope I'm not breaking rules posting a feature request here, but I haven't seen any traction on the following feature request at the HA community forum and thought this might be my best avenue.

https://community.home-assistant.io/t/lutron-appliance-module-support-for-the-lutron-caseta-integration/297499

:)

**Comment by mdonoughe** [comment]
Do you have one? The appropriate name needs to be added to this list: https://github.com/gurumitts/pylutron-caseta/blob/dev/pylutron_caseta/__init__.py#L9-L12

**Comment by YourMom11** [comment]
I do have one. I am not entirely sure of the precise name. Perhaps something like 'PlugInAppliance'. Photo attached.

I'm happy to test for you.

Also, here is the [spec sheet](https://www.lutron.com/TechnicalDocumentLibrary/369246_ENG.pdf) if that's any help.

![IMG_5714](https://user-images.githubusercontent.com/6014317/120249677-e1f7c280-c238-11eb-9906-94e07580c6cb.jpg)

**Comment by mdonoughe** [comment]
If you enable debug logging I think it will come out there.

How to configure logging in Home Assistant: https://www.home-assistant.io/integrations/logger/

If you enable debug logging for pylutron_caseta.leap it should come out for sure, but I think pylutron_caseta.smartbridge will also log it, and maybe in an easier to recognize format and with less noise. You're looking for "DeviceType" or "type".

**Comment by YourMom11** [comment]
Is this what you're looking for?

[pylutron_caseta.smartbridge] Requesting zone information from {'device_id': '4', 'current_state': -1, 'fan_speed': None, 'zone': '2', 'name': 'Counter_Coffee Machine', 'type': 'PlugInSwitch', 'model': 'RR-15APS-1-XX', 'serial': 67958053}

**Comment by mdonoughe** [comment]
Yes. PlugInSwitch should be added to the switch section in that Python file.

**Comment by YourMom11** [comment]
Great. I don't have Write access to the referenced file. It would also be my first Commit. Is this something you can do for me please?

**Comment by mdonoughe** [comment]
On GitHub normally you make a fork of the repository and then start a pull request. If you click the fork button near the top of the page you'll get a YourMom11/pylutron-caseta that you have full control over, and then once you have a branch there you can open a PR back to here.

**Comment by YourMom11** [comment]
I think I did it. Thank you :)

**Comment by mdonoughe** [comment]
I merged #76 and released 0.11.0 to PyPI. If you want to get it running in Home Assistant without waiting for a new release or switching your whole house over to a nightly build, I think you can manually install a copy of it into config/deps/lib/python3.8/site-packages and restart Home Assistant. On my system it looks like this:
![image](https://user-images.githubusercontent.com/17961/120409392-cff04f80-c31e-11eb-9399-62396f57190f.png)

Since pylutron_caseta 0.11.0 will advertise the device as a switch it should get picked up by Home Assistant and appear as a device without requiring any other changes.

**Comment by YourMom11** [comment]
I had to create lib/python3.8/site-packages since /deps was empty.

I dropped 'pylutron-caseta-0.11.0' into there and restarted, but no luck. What am I missing?

**Comment by mdonoughe** [comment]
The dist-info folder has the version number on it, but the main folder with the library files in it does not. I don't know if you need the dist-info folder. If you need that stuff you should be able to pip install the package to there with the -t option.

**Comment by YourMom11** [comment]
Thank you so much for your help. I'm very appreciative for all your Github guidance as well
