### ISSUE TITLE
Working with OpenHAB 3

### ISSUE THREAD

**Issue by GregoryWest501** [gurumitts/pylutron-caseta#79]
Working with your script with OH3.  The script runs fine and generates the three files.  One issue is the script never asked me for a password.  Not sure what to tell OH3 for the password.

Anyone using this script with OH3?

Greg

**Comment by mdonoughe** [comment]
Password sounds like OpenHAB 3 authenticates via Lutron's cloud service. pylutron-caseta has not needed any passwords since version 0.6.0 released 2020-03-22.

**Comment by GregoryWest501** [comment]
Of the three files your script which one would be the 'keystone' file?  Or is the keystone file something from the cloud service?

**Comment by mdonoughe** [comment]
https://www.openhab.org/addons/bindings/lutron/doc/leapnotes.html

You need to create a keystore file following these instructions.

**Comment by GregoryWest501** [comment]
Thank you Thank you Thank you!!!    Everything looks like it is working now!
