### ISSUE TITLE
Refactor for getting devices by HA type

### ISSUE THREAD

**Issue by upsert** [gurumitts/pylutron-caseta#8]
As per comments in home-assistant/home-assistant#8903, the Home Assistant authors have suggested having a method to retrieve devices by their HA type such as 'light', 'switch' and 'cover'. The refactor is needed before support for Triathlon shades can be added.

For reference, find below all the device types supported on the LEAP interface. Includes a sensor type in anticipation of one day supporting Pico remotes which will become sensors.

 'light'
---------- |
 WallDimmer
 PlugInDimmer

 'switch'
---------- |
WallSwitch

'cover'
-------- |
SerenaHoneycombShade
SerenaRollerShade
TriathlonHoneycombShade
TriathlonRollerShade
QsWirelessShade

'sensor'
-------- |
Pico1Button
Pico2Button
Pico2ButtonRaiseLower
Pico3Button
Pico3ButtonRaiseLower
Pico4Button
Pico4ButtonScene
Pico4ButtonZone
Pico4Button2Group
FourGroupRemote

Other Device Types
------------------ |
SmartBridge

@gurumitts I hope you don't mind if I add a few issues and if I can learn a bit more Python, hopefully I'll contribute some code too. I'll also try to write up what I've learned about the interfaces.

**Comment by gurumitts** [comment]
No issue at all.  =)

**Comment by gurumitts** [comment]
Changes are now live in version 0.2.8.  https://pypi.python.org/pypi/pylutron_caseta/0.2.8
