### ISSUE TITLE
Add telnet support for Smart Bridge Pro

### ISSUE THREAD

**Issue by upsert** [gurumitts/pylutron-caseta#9]
**TODO:** Add telnet support to support events from Pico remotes on the Smart Bridge Pro. Also needed to support arbitrary fade and/or delay time on any dimmer commands.

A hybrid of SSH and Telnet needs to be supported to get the best features from both types of Smart Bridges. After initial configuration, only one of the interfaces needs to be monitored for events (Telnet for Pro, SSH for non-Pro).

Pro bridge support through the Telnet interface adds a tremendous value by supporting any Pico as a scene controller and in combination with [Home Assistant](https://home-assistant.io/), can trigger any automation. For example, a four button Pico could be used as a fan speed controller with a Z-Wave fan switch.

**Comment by swails** [comment]
Home Assistant already has a telnet-based Lutron plugin.  Just use that for the Caseta Smart Bridge Pro, or am I missing something?

**Comment by mdonoughe** [comment]
I'm going to close this one. The Telnet interface on the Pro bridge uses the LIP protocol, which is significantly different from the LEAP protocol used by pylutron-caseta since SSH was removed.

**Comment by swails** [comment]
There's also another library (pylutron) that speaks LIP, so you could (and should) just use that.
