### ISSUE TITLE
Question: Does this library work with RadioRA 3 All-in-One Processor?

### ISSUE THREAD

**Issue by jeremyprz** [gurumitts/pylutron-caseta#92]
Does this library work with RadioRA 3 All-in-One Processor model number `RR-PROC3-KIT`?

I'd like to standardize my systems to use this library. I've confirmed the functionality I need works with the caseta bridge and am considering the RadioRA3 devices - but I don't want to purchase and experiment if anyone definitively knows this library does not work with the RadioRA3 processor.

**Comment by jeremyprz** [comment]
Even if @gurumitts or other primary contributors can say `unsure` or `possibly, but untested` - both are very useful information.

**Comment by swails** [comment]
There are pull requests in the works on this repo specifically to add support for RA3

**Comment by jeremyprz** [comment]
@swails Thanks for the info, this is helpful. I already have sunk-cost into 2x caseta bridges and they will suffice for my installation for the moment. If my installation expands beyond what is supported by caseta, I'll check back for RA3 support.

**Comment by elreydetodo** [comment]
#101 just merged with support for RA3.
