### ISSUE TITLE
Support for RF Modules

### ISSUE THREAD

**Issue by iCSpotRun** [gurumitts/pylutron-caseta#98]
Hoping support for the following two devices can be added. These devices work across most Lutron systems (RA2, RA2S, RA3).

0-10V RF Dimming Module
Model: LMJ-5T-DV-B

RF Relay Module with Softswitch
Model: LMJ-16R-DV-B

I currently do not have these devices on hand, but can supply them to you if required.

**Comment by mdonoughe** [comment]
Do you know how they identify themselves? The current version of pylutron-caseta only works with devices on these lists: https://github.com/gurumitts/pylutron-caseta/blob/dev/pylutron_caseta/__init__.py#L8-L13 .

**Comment by danaues** [comment]
Looking through the linked notes provided from this system, these devices identify themselves as "Switched" and "Dimmed" (on RA3 anyway), so they will probably work fine with PR#101 that has already been merged.

https://gist.github.com/dcode/1fa9684f619fe6d9d53321c477ca91cf
